### ISSUE TITLE
How to use "classes" in the config

### ISSUE THREAD

**Issue by seattlecajun** [rmrustem/MMM-quotes#2]
What is the proper way to utilize the 'classes' mentioned in your configuration options? I'd like to use some other MM default styles and can't figure out how to format them properly. Specifically, it defaults to 'medium' and 'bright'. I'd like to use 'large' instead of medium.  Thanks.

**Comment by rmrustem** [comment]
There are 2 options for that, one for the quote, `classes`, and the other for the author name, `authorClasses`. These options can be overwritten inside the `config` dict, e.g.:
```javascript
modules: [
  ...
  {
    module: 'MMM-quotes',
    position: 'lower_third',
    config: {
      classes: 'large bright',
      authorClasses: 'medium normal align-right'
    }
  },
  ...
]
````
